# src/main/resources/application.yml
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

# Include the external configuration file for client ID-user mappings
spring:
  config:
    import: client-mappings.yml
